/**
 * Supabase Edge Function: send-auth-email
 *
 * Supabase Auth "Send Email Hook". With the hook enabled, Supabase stops
 * sending its own auth emails and POSTs every one here instead: signup
 * verification, password reset, magic link, invite, email change and
 * reauthentication. We render a branded bilingual email and send it through
 * Resend (see `../_shared/email.ts`).
 *
 * Both clients benefit with no code change: the web app
 * (`AuthContext.signUp` / `resetPassword`) and the Flutter app
 * (`auth_repository.dart`) keep calling supabase-js/supabase-dart as before.
 *
 * ── Secrets ─────────────────────────────────────────────────────────────────
 *   SEND_EMAIL_HOOK_SECRET  `v1,whsec_…`, generated by the dashboard when the
 *                           hook is created (Auth → Hooks → Send Email).
 *   + RESEND_API_KEY / EMAIL_FROM / SITE_URL (see _shared/email.ts)
 *
 * ── Deploy ──────────────────────────────────────────────────────────────────
 *   supabase functions deploy send-auth-email --no-verify-jwt
 *
 * No JWT: the caller is Supabase Auth itself. Every request is authenticated
 * by its Standard Webhooks signature instead, verified below.
 *
 * ── Failure mode ────────────────────────────────────────────────────────────
 * A non-2xx here makes the originating auth call (signUp, resetPasswordForEmail)
 * fail with the message we return, so the user sees an error instead of
 * waiting for an email that is never coming.
 */

import { Webhook } from "https://esm.sh/standardwebhooks@1.0.0";
import { EmailContent, render, sendEmail } from "../_shared/email.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const HOOK_SECRET = (Deno.env.get("SEND_EMAIL_HOOK_SECRET") ?? "").replace(
  /^v1,whsec_/,
  "",
);

type ActionType =
  | "signup"
  | "recovery"
  | "invite"
  | "magiclink"
  | "email_change"
  | "email"
  | "reauthentication";

interface HookPayload {
  user: {
    id: string;
    email: string;
    new_email?: string;
    user_metadata?: { full_name?: string };
  };
  email_data: {
    token: string;
    token_hash: string;
    redirect_to: string;
    email_action_type: ActionType;
    site_url: string;
    token_new: string;
    token_hash_new: string;
  };
}

function fail(status: number, message: string): Response {
  return new Response(
    JSON.stringify({ error: { http_code: status, message } }),
    { status, headers: { "Content-Type": "application/json" } },
  );
}

function verifyUrl(tokenHash: string, type: string, redirectTo: string): string {
  const u = new URL(`${SUPABASE_URL}/auth/v1/verify`);
  u.searchParams.set("token", tokenHash);
  u.searchParams.set("type", type);
  if (redirectTo) u.searchParams.set("redirect_to", redirectTo);
  return u.toString();
}

function greeting(name: string | undefined, lang: "ar" | "en"): string {
  const n = (name ?? "").trim();
  if (lang === "ar") return n ? `مرحباً ${n}،` : "مرحباً،";
  return n ? `Hi ${n},` : "Hi,";
}

const IGNORE_AR = "إن لم تطلب ذلك فتجاهل هذه الرسالة، ولن يتغيّر شيء في حسابك.";
const IGNORE_EN = "If you didn't ask for this, ignore this email — nothing about your account changes.";

function build(
  type: ActionType,
  name: string | undefined,
  url: string,
  code: string,
): EmailContent {
  const hiAr = greeting(name, "ar");
  const hiEn = greeting(name, "en");
  switch (type) {
    case "signup":
      return {
        tag: "auth_signup",
        subject: "أكّد بريدك الإلكتروني · Confirm your email",
        url,
        code,
        ar: {
          heading: "أهلاً بك في ورق أكاديمي",
          body: [hiAr, "خطوة واحدة بقيت: أكّد بريدك الإلكتروني لتفعيل حسابك وتبدأ التعلّم."],
          cta: "تأكيد البريد الإلكتروني",
          footnote: `أو أدخل الرمز أعلاه في التطبيق. ${IGNORE_AR}`,
        },
        en: {
          heading: "Welcome to Waraq Academy",
          body: [hiEn, "One step left: confirm your email to activate your account and start learning."],
          cta: "Confirm email",
          footnote: `Or enter the code above in the app. ${IGNORE_EN}`,
        },
      };
    case "recovery":
      return {
        tag: "auth_recovery",
        subject: "إعادة تعيين كلمة المرور · Reset your password",
        url,
        code,
        ar: {
          heading: "إعادة تعيين كلمة المرور",
          body: [hiAr, "وصلنا طلب لإعادة تعيين كلمة مرور حسابك. اضغط الزر لاختيار كلمة مرور جديدة. الرابط صالح لمدة ساعة واحدة."],
          cta: "اختيار كلمة مرور جديدة",
          footnote: IGNORE_AR,
        },
        en: {
          heading: "Reset your password",
          body: [hiEn, "We received a request to reset your password. Use the button to choose a new one. The link is valid for one hour."],
          cta: "Choose a new password",
          footnote: IGNORE_EN,
        },
      };
    case "invite":
      return {
        tag: "auth_invite",
        subject: "دعوة للانضمام إلى ورق أكاديمي · You're invited to Waraq Academy",
        url,
        ar: {
          heading: "لديك دعوة",
          body: [hiAr, "تمت دعوتك للانضمام إلى ورق أكاديمي. اضغط الزر لقبول الدعوة وإعداد حسابك."],
          cta: "قبول الدعوة",
        },
        en: {
          heading: "You're invited",
          body: [hiEn, "You've been invited to join Waraq Academy. Accept the invite to set up your account."],
          cta: "Accept invite",
        },
      };
    case "magiclink":
      return {
        tag: "auth_magiclink",
        subject: "رابط تسجيل الدخول · Your sign-in link",
        url,
        code,
        ar: {
          heading: "تسجيل الدخول",
          body: [hiAr, "اضغط الزر لتسجيل الدخول إلى حسابك. الرابط يُستخدم مرة واحدة."],
          cta: "تسجيل الدخول",
          footnote: IGNORE_AR,
        },
        en: {
          heading: "Sign in",
          body: [hiEn, "Use the button to sign in. The link works once."],
          cta: "Sign in",
          footnote: IGNORE_EN,
        },
      };
    case "email_change":
    case "email":
      return {
        tag: "auth_email_change",
        subject: "تأكيد تغيير البريد الإلكتروني · Confirm your email change",
        url,
        code,
        ar: {
          heading: "تأكيد تغيير البريد الإلكتروني",
          body: [hiAr, "اضغط الزر لتأكيد تغيير البريد الإلكتروني المرتبط بحسابك."],
          cta: "تأكيد التغيير",
          footnote: IGNORE_AR,
        },
        en: {
          heading: "Confirm your email change",
          body: [hiEn, "Use the button to confirm the change to the email on your account."],
          cta: "Confirm change",
          footnote: IGNORE_EN,
        },
      };
    case "reauthentication":
      return {
        tag: "auth_reauth",
        subject: "رمز التحقق · Your verification code",
        code,
        ar: {
          heading: "رمز التحقق",
          body: [hiAr, "أدخل هذا الرمز لتأكيد العملية:"],
          footnote: IGNORE_AR,
        },
        en: {
          heading: "Verification code",
          body: [hiEn, "Enter this code to confirm the action:"],
          footnote: IGNORE_EN,
        },
      };
  }
}

Deno.serve(async (req) => {
  if (req.method !== "POST") return fail(405, "Method not allowed");
  if (!HOOK_SECRET) return fail(500, "SEND_EMAIL_HOOK_SECRET is not set");

  const raw = await req.text();
  let payload: HookPayload;
  try {
    payload = new Webhook(HOOK_SECRET).verify(
      raw,
      Object.fromEntries(req.headers),
    ) as HookPayload;
  } catch {
    return fail(401, "Invalid webhook signature");
  }

  const { user, email_data: d } = payload;
  const name = user.user_metadata?.full_name;
  const type = d.email_action_type;
  const redirectTo = d.redirect_to || d.site_url;

  try {
    const jobs: Promise<string>[] = [];

    if (type === "email_change" && d.token_hash_new) {
      // Secure email change: both addresses must confirm. Per the Supabase hook
      // contract, token_hash_new pairs with the CURRENT address and token_hash
      // with the NEW one (the naming is historical).
      const toCurrent = render(build(type, name, verifyUrl(d.token_hash_new, type, redirectTo), d.token));
      const toNew = render(build(type, name, verifyUrl(d.token_hash, type, redirectTo), d.token_new));
      jobs.push(sendEmail({ to: user.email, ...toCurrent, idempotencyKey: `auth-${d.token_hash_new}`, tags: [{ name: "type", value: "auth_email_change" }] }));
      if (user.new_email) {
        jobs.push(sendEmail({ to: user.new_email, ...toNew, idempotencyKey: `auth-${d.token_hash}`, tags: [{ name: "type", value: "auth_email_change" }] }));
      }
    } else {
      const to = type === "email_change" && user.new_email ? user.new_email : user.email;
      const content = build(type, name, verifyUrl(d.token_hash, type, redirectTo), d.token);
      if (!content) return fail(400, `Unsupported email_action_type: ${type}`);
      jobs.push(sendEmail({
        to,
        ...render(content),
        idempotencyKey: `auth-${d.token_hash || d.token}`,
        tags: [{ name: "type", value: content.tag }],
      }));
    }

    await Promise.all(jobs);
    return new Response("{}", { status: 200, headers: { "Content-Type": "application/json" } });
  } catch (err) {
    console.error("send-auth-email failed", type, err);
    return fail(500, err instanceof Error ? err.message : "Email send failed");
  }
});
